---
parent: 'common/test_cases/origin.yml'
extensions:
  sync_repos:
    - name: "openshift-ansible"
    - name: "aos-cd-jobs"
  actions:
    - type: "script"
      title: "build an origin release"
      repository: "origin"
      script: |-
        hack/build-base-images.sh
        OS_BUILD_ENV_PRESERVE=_output/local hack/env hack/build-rpm-release.sh
        sudo systemctl restart docker
        hack/build-images.sh
        sed -i 's|go/src|data/src|' _output/local/releases/rpms/origin-local-release.repo
        sudo cp _output/local/releases/rpms/origin-local-release.repo /etc/yum.repos.d/
    - type: "script"
      title: "build an openshift-ansible release"
      repository: "openshift-ansible"
      script: |-
        tito_tmp_dir="tito"
        mkdir -p "${tito_tmp_dir}"
        tito tag --offline --use-version 3.6.0 --accept-auto-changelog
        tito build --output="${tito_tmp_dir}" --rpm --test --offline --quiet
        createrepo "${tito_tmp_dir}/noarch"
        cat << EOR > ./openshift-ansible-local-release.repo
        [openshift-ansible-local-release]
        baseurl = file://$( pwd )/${tito_tmp_dir}/noarch
        gpgcheck = 0
        name = OpenShift Ansible Release from Local Source
        EOR
        sudo cp ./openshift-ansible-local-release.repo /etc/yum.repos.d
    - type: "script"
      title: "install the openshift-ansible release"
      script: |-
        sudo yum install -y atomic-openshift-utils
    - type: "script"
      title: "check out the correct branch of aos-cd-jobs"
      repository: "aos-cd-jobs"
      script: |-
        git checkout sjb
    - type: "script"
      title: "determine the release commit for origin images"
      repository: "origin"
      script: |-
        git log -1 --pretty=%h >> /data/src/github.com/openshift/aos-cd-jobs/ORIGIN_COMMIT
    - type: "script"
      title: "install origin"
      repository: "aos-cd-jobs"
      script: |-
        ansible-playbook --become --become-user root --connection local --inventory inventory/ /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-node/network_manager.yml
        ansible-playbook --become --become-user root --connection local --inventory inventory/ /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml -e openshift_image_tag="$( cat ./ORIGIN_COMMIT )"
    - type: "script"
      title: "expose the kubeconfig"
      script: |-
        sudo chmod a+x /etc/ /etc/origin/ /etc/origin/master/
        sudo chmod a+rw /etc/origin/master/admin.kubeconfig
    - type: "script"
      title: "run extended tests"
      repository: "origin"
      script: |-
        KUBECONFIG=/etc/origin/master/admin.kubeconfig TEST_ONLY='true' JUNIT_REPORT='true' make test-extended SUITE=conformance